# Generated by Django 6.0.3 on 2026-03-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('study_design', 'Study Design'), ('setting', 'Setting'), ('population_type', 'Population Type'), ('assessment_tool', 'Assessment Tool'), ('tool_usage_type', 'Tool Usage Type'), ('outcome_domain', 'Outcome Domain')], db_index=True, max_length=50)),
                ('label', models.CharField(help_text='Full display name, e.g. "Child and Adolescent Needs and Strengths"', max_length=255)),
                ('abbreviation', models.CharField(blank=True, help_text='Short form, e.g. "CANS"', max_length=50)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved terms appear in user-facing dropdowns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(blank=True, help_text='Null if seeded by admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'label'],
                'unique_together': {('category', 'label')},
            },
        ),
    ]
