# Generated by Django 6.0.3 on 2026-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_controlledterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pmid', models.CharField(blank=True, help_text='PubMed ID', max_length=50)),
                ('arxiv_id', models.CharField(blank=True, max_length=50)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('publication_type', models.CharField(choices=[('journal_article', 'Journal Article'), ('conference', 'Conference Paper'), ('report', 'Report'), ('thesis', 'Thesis'), ('book_chapter', 'Book Chapter'), ('book', 'Book'), ('other', 'Other')], default='journal_article', max_length=50)),
                ('journal', models.CharField(blank=True, help_text='Journal name. Stored as text for now, can be normalised later.', max_length=255)),
                ('raw_metadata', models.TextField(blank=True, help_text='Raw API response from Crossref or PubMed stored as JSON string.')),
                ('metadata_source', models.CharField(choices=[('crossref', 'Crossref'), ('pubmed', 'PubMed'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', max_length=50)),
                ('inclusion_status', models.CharField(choices=[('candidate', 'Candidate'), ('included', 'Included'), ('excluded', 'Excluded')], default='candidate', max_length=50)),
                ('exclusion_reason', models.TextField(blank=True, help_text='Required when inclusion_status is excluded.')),
                ('curation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
