# Generated by Django 6.0.3 on 2026-03-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicationassignment_workflowtransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('human', 'Human'), ('llm', 'LLM')], default='human', max_length=10)),
                ('llm_model', models.CharField(blank=True, help_text='Model identifier if reviewer_type is LLM, e.g. claude-sonnet-4-6.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='core.publication')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Null if this is an LLM extraction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('publication', 'reviewer')},
            },
        ),
    ]
