# Generated by Django 6.0.3 on 2026-03-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_extractionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_as', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('sample_size', models.PositiveIntegerField(blank=True, help_text='Number of participants assessed with this tool, if reported separately.', null=True)),
                ('age_range_min', models.PositiveIntegerField(blank=True, help_text='Minimum age of participants assessed with this tool.', null=True)),
                ('age_range_max', models.PositiveIntegerField(blank=True, help_text='Maximum age of participants assessed with this tool.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tool_usages', to='core.extractionrecord')),
                ('population_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'population_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_tool_usages_by_population', to='core.controlledterm')),
                ('tool', models.ForeignKey(limit_choices_to={'category': 'assessment_tool'}, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_tool_usages', to='core.controlledterm')),
            ],
            options={
                'ordering': ['extraction', 'tool'],
                'unique_together': {('extraction', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sample_size', models.PositiveIntegerField(blank=True, help_text='Total number of participants across the full study.', null=True)),
                ('country', models.CharField(blank=True, help_text='Primary country where the study was conducted.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any additional study-level observations.')),
                ('extraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_profile', to='core.extractionrecord')),
                ('setting', models.ForeignKey(blank=True, limit_choices_to={'category': 'setting'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_profiles_by_setting', to='core.controlledterm')),
                ('study_design', models.ForeignKey(blank=True, limit_choices_to={'category': 'study_design'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_profiles_by_design', to='core.controlledterm')),
            ],
            options={
                'ordering': ['extraction'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, choices=[('improvement', 'Improvement'), ('decline', 'Decline'), ('mixed', 'Mixed'), ('null', 'Null / No significant change')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessment_tool_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_domains', to='core.assessmenttoolusage')),
                ('domain', models.ForeignKey(limit_choices_to={'category': 'outcome_domain'}, on_delete=django.db.models.deletion.PROTECT, related_name='outcome_domains', to='core.controlledterm')),
            ],
            options={
                'ordering': ['assessment_tool_usage', 'domain'],
                'unique_together': {('assessment_tool_usage', 'domain')},
            },
        ),
    ]
