# Generated by Django 6.0.3 on 2026-03-05 23:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assessmenttoolusage_studyprofile_outcomedomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Set when the reviewer records their decision.', null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Required when decision is rejected or needs revision.')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.extractionrecord')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Null until a reviewer claims or is assigned to this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssessmentToolUsage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('used_as', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('sample_size', models.PositiveIntegerField(blank=True, help_text='Number of participants assessed with this tool, if reported separately.', null=True)),
                ('age_range_min', models.PositiveIntegerField(blank=True, help_text='Minimum age of participants assessed with this tool.', null=True)),
                ('age_range_max', models.PositiveIntegerField(blank=True, help_text='Maximum age of participants assessed with this tool.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extraction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.extractionrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('population_type', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'population_type'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
                ('tool', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'assessment_tool'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
            ],
            options={
                'verbose_name': 'historical assessment tool usage',
                'verbose_name_plural': 'historical assessment tool usages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExtractionRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('human', 'Human'), ('llm', 'LLM')], default='human', max_length=10)),
                ('llm_model', models.CharField(blank=True, help_text='Model identifier if reviewer_type is LLM, e.g. claude-sonnet-4-6.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.publication')),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, help_text='Null if this is an LLM extraction.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical extraction record',
                'verbose_name_plural': 'historical extraction records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOutcomeDomain',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('direction', models.CharField(blank=True, choices=[('improvement', 'Improvement'), ('decline', 'Decline'), ('mixed', 'Mixed'), ('null', 'Null / No significant change')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assessment_tool_usage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.assessmenttoolusage')),
                ('domain', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'outcome_domain'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical outcome domain',
                'verbose_name_plural': 'historical outcome domains',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudyProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('overall_sample_size', models.PositiveIntegerField(blank=True, help_text='Total number of participants across the full study.', null=True)),
                ('country', models.CharField(blank=True, help_text='Primary country where the study was conducted.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any additional study-level observations.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extraction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.extractionrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'setting'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
                ('study_design', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'study_design'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
            ],
            options={
                'verbose_name': 'historical study profile',
                'verbose_name_plural': 'historical study profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
