# Generated by Django 6.0.3 on 2026-03-08 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_extractionreview_historicalassessmenttoolusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete. Hidden from normal views. Only removable by superusers.'),
        ),
        migrations.AddField(
            model_name='extractionreview',
            name='quality_score',
            field=models.IntegerField(blank=True, help_text='Quality score from 1 (poor) to 10 (excellent).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='historicalextractionrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete. Hidden from normal views. Only removable by superusers.'),
        ),
    ]
