# Generated by Django 6.0.3 on 2026-03-17 18:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publication_submitted_by_deletionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttoolusage',
            name='administration_timing',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('intake', 'Intake / Baseline'), ('discharge', 'Discharge'), ('follow_up', 'Follow-up'), ('cross_sectional', 'Cross-sectional'), ('multiple', 'Multiple timepoints'), ('other', 'Other')], help_text='When the tool was administered relative to the study timeline.', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmenttoolusage',
            name='sample_descriptor',
            field=models.TextField(blank=True, help_text='Description of the sample assessed with this tool.'),
        ),
        migrations.AddField(
            model_name='assessmenttoolusage',
            name='scoring_method',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('total_score', 'Total score'), ('subscale', 'Subscale score'), ('cutoff', 'Cutoff / threshold'), ('change_score', 'Change score'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalassessmenttoolusage',
            name='administration_timing',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('intake', 'Intake / Baseline'), ('discharge', 'Discharge'), ('follow_up', 'Follow-up'), ('cross_sectional', 'Cross-sectional'), ('multiple', 'Multiple timepoints'), ('other', 'Other')], help_text='When the tool was administered relative to the study timeline.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalassessmenttoolusage',
            name='sample_descriptor',
            field=models.TextField(blank=True, help_text='Description of the sample assessed with this tool.'),
        ),
        migrations.AddField(
            model_name='historicalassessmenttoolusage',
            name='scoring_method',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('total_score', 'Total score'), ('subscale', 'Subscale score'), ('cutoff', 'Cutoff / threshold'), ('change_score', 'Change score'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='confidence_interval',
            field=models.CharField(blank=True, help_text='e.g. "0.23-0.45" or "95% CI: 1.2-3.4"', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='effect_size_type',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('beta', 'Beta coefficient'), ('or', 'Odds ratio (OR)'), ('rr', 'Risk ratio (RR)'), ('mean_diff', 'Mean difference'), ('cohen_d', "Cohen's d"), ('r', 'Correlation (r)'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='effect_size_value',
            field=models.FloatField(blank=True, help_text='Numeric effect size value.', null=True),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='is_case_control',
            field=models.BooleanField(default=False, help_text='Whether this outcome is from a case-control comparison.'),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='outcome_metric',
            field=models.TextField(blank=True, help_text='Specific metric used to measure this outcome.'),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='p_value',
            field=models.CharField(blank=True, help_text='e.g. "0.032" or "<0.001". Stored as text to preserve original reporting.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='predictor',
            field=models.TextField(blank=True, help_text='Predictor associated with this outcome if applicable.'),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='result_description',
            field=models.TextField(blank=True, help_text='Short description of the result as reported in the paper.'),
        ),
        migrations.AddField(
            model_name='historicaloutcomedomain',
            name='significance',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('significant', 'Statistically significant'), ('not_significant', 'Not statistically significant'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='conflicts_of_interest',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('yes', 'Yes'), ('no', 'No'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='exclusion_criteria',
            field=models.TextField(blank=True, help_text='Participant exclusion criteria as reported.'),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='follow_up_duration',
            field=models.CharField(blank=True, help_text='Description of follow-up duration if longitudinal.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('government', 'Government'), ('industry', 'Industry'), ('nonprofit', 'Nonprofit / Foundation'), ('university', 'University / Academic'), ('mixed', 'Mixed'), ('none', 'No funding reported'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='inclusion_criteria',
            field=models.TextField(blank=True, help_text='Participant inclusion criteria as reported.'),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='study_duration_years',
            field=models.FloatField(blank=True, help_text='Years of cross-sectional data or duration of follow-up.', null=True),
        ),
        migrations.AddField(
            model_name='historicalstudyprofile',
            name='us_state',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands'), ('GU', 'Guam')], help_text='US state if applicable.', max_length=2),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='confidence_interval',
            field=models.CharField(blank=True, help_text='e.g. "0.23-0.45" or "95% CI: 1.2-3.4"', max_length=50),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='effect_size_type',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('beta', 'Beta coefficient'), ('or', 'Odds ratio (OR)'), ('rr', 'Risk ratio (RR)'), ('mean_diff', 'Mean difference'), ('cohen_d', "Cohen's d"), ('r', 'Correlation (r)'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='effect_size_value',
            field=models.FloatField(blank=True, help_text='Numeric effect size value.', null=True),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='is_case_control',
            field=models.BooleanField(default=False, help_text='Whether this outcome is from a case-control comparison.'),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='outcome_metric',
            field=models.TextField(blank=True, help_text='Specific metric used to measure this outcome.'),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='p_value',
            field=models.CharField(blank=True, help_text='e.g. "0.032" or "<0.001". Stored as text to preserve original reporting.', max_length=50),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='predictor',
            field=models.TextField(blank=True, help_text='Predictor associated with this outcome if applicable.'),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='result_description',
            field=models.TextField(blank=True, help_text='Short description of the result as reported in the paper.'),
        ),
        migrations.AddField(
            model_name='outcomedomain',
            name='significance',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('significant', 'Statistically significant'), ('not_significant', 'Not statistically significant'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='conflicts_of_interest',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('yes', 'Yes'), ('no', 'No'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='exclusion_criteria',
            field=models.TextField(blank=True, help_text='Participant exclusion criteria as reported.'),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='follow_up_duration',
            field=models.CharField(blank=True, help_text='Description of follow-up duration if longitudinal.', max_length=200),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('government', 'Government'), ('industry', 'Industry'), ('nonprofit', 'Nonprofit / Foundation'), ('university', 'University / Academic'), ('mixed', 'Mixed'), ('none', 'No funding reported'), ('unclear', 'Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='inclusion_criteria',
            field=models.TextField(blank=True, help_text='Participant inclusion criteria as reported.'),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='study_duration_years',
            field=models.FloatField(blank=True, help_text='Years of cross-sectional data or duration of follow-up.', null=True),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='us_state',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands'), ('GU', 'Guam')], help_text='US state if applicable.', max_length=2),
        ),
        migrations.AlterField(
            model_name='controlledterm',
            name='category',
            field=models.CharField(choices=[('study_design', 'Study Design'), ('setting', 'Setting'), ('population_type', 'Population Type'), ('assessment_tool', 'Assessment Tool'), ('tool_usage_type', 'Tool Usage Type'), ('administration_context', 'Administration Context'), ('outcome_domain', 'Outcome Domain'), ('statistical_method', 'Statistical Method'), ('predictor_category', 'Predictor / Covariate Category'), ('feedback_category', 'Feedback Category')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricalPredictorCovariate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Specific predictor or covariate as described in the paper.')),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'predictor_category'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
                ('extraction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.extractionrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical predictor covariate',
                'verbose_name_plural': 'historical predictor covariates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiskOfBiasAssessment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('framework', models.CharField(blank=True, choices=[('rob2', 'Cochrane RoB 2 (RCTs)'), ('robins_i', 'ROBINS-I (Observational)'), ('other', 'Other')], max_length=20)),
                ('overall_rating', models.CharField(blank=True, choices=[('low', 'Low'), ('some_concerns', 'Some Concerns'), ('high', 'High'), ('critical', 'Critical'), ('unclear', 'Unclear')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extraction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.extractionrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Risk of Bias Assessment',
                'verbose_name_plural': 'historical Risk of Bias Assessments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStatisticalMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('method_category', models.CharField(blank=True, choices=[('regression', 'Regression (continuous outcome)'), ('classification', 'Classification (discrete outcome)'), ('reliability', 'Reliability'), ('validity', 'Validity'), ('descriptive', 'Descriptive'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extraction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.extractionrecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method_name', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'statistical_method'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.controlledterm')),
            ],
            options={
                'verbose_name': 'historical statistical method',
                'verbose_name_plural': 'historical statistical methods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudyDemographics',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('percent_female', models.FloatField(blank=True, help_text='Percentage of female participants (0-100).', null=True)),
                ('percent_male', models.FloatField(blank=True, help_text='Percentage of male participants (0-100).', null=True)),
                ('age_range_min', models.PositiveIntegerField(blank=True, help_text='Minimum age of participants in years.', null=True)),
                ('age_range_max', models.PositiveIntegerField(blank=True, help_text='Maximum age of participants in years.', null=True)),
                ('age_notes', models.CharField(blank=True, help_text='e.g. "mean age 12.3" or age reporting details.', max_length=200)),
                ('race_distribution', models.TextField(blank=True, help_text='Race/ethnicity distribution as reported. Free text due to inconsistent reporting across studies.')),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.studyprofile')),
            ],
            options={
                'verbose_name': 'historical Study Demographics',
                'verbose_name_plural': 'historical Study Demographics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PredictorCovariate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Specific predictor or covariate as described in the paper.')),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'category': 'predictor_category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictors_by_category', to='core.controlledterm')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictors', to='core.extractionrecord')),
            ],
            options={
                'ordering': ['extraction', 'category'],
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(blank=True, choices=[('rob2', 'Cochrane RoB 2 (RCTs)'), ('robins_i', 'ROBINS-I (Observational)'), ('other', 'Other')], max_length=20)),
                ('overall_rating', models.CharField(blank=True, choices=[('low', 'Low'), ('some_concerns', 'Some Concerns'), ('high', 'High'), ('critical', 'Critical'), ('unclear', 'Unclear')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('extraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_of_bias', to='core.extractionrecord')),
            ],
            options={
                'verbose_name': 'Risk of Bias Assessment',
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='e.g. "Randomization process" or "Missing outcome data"', max_length=200)),
                ('rating', models.CharField(blank=True, choices=[('low', 'Low'), ('some_concerns', 'Some Concerns'), ('high', 'High'), ('na', 'Not Applicable'), ('unclear', 'Unclear')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.riskofbiasassessment')),
            ],
            options={
                'ordering': ['assessment', 'domain_name'],
            },
        ),
        migrations.CreateModel(
            name='StatisticalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_category', models.CharField(blank=True, choices=[('regression', 'Regression (continuous outcome)'), ('classification', 'Classification (discrete outcome)'), ('reliability', 'Reliability'), ('validity', 'Validity'), ('descriptive', 'Descriptive'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistical_methods', to='core.extractionrecord')),
                ('method_name', models.ForeignKey(blank=True, limit_choices_to={'category': 'statistical_method'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistical_methods', to='core.controlledterm')),
            ],
            options={
                'ordering': ['extraction', 'method_category'],
            },
        ),
        migrations.CreateModel(
            name='StudyDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_female', models.FloatField(blank=True, help_text='Percentage of female participants (0-100).', null=True)),
                ('percent_male', models.FloatField(blank=True, help_text='Percentage of male participants (0-100).', null=True)),
                ('age_range_min', models.PositiveIntegerField(blank=True, help_text='Minimum age of participants in years.', null=True)),
                ('age_range_max', models.PositiveIntegerField(blank=True, help_text='Maximum age of participants in years.', null=True)),
                ('age_notes', models.CharField(blank=True, help_text='e.g. "mean age 12.3" or age reporting details.', max_length=200)),
                ('race_distribution', models.TextField(blank=True, help_text='Race/ethnicity distribution as reported. Free text due to inconsistent reporting across studies.')),
                ('notes', models.TextField(blank=True)),
                ('study_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.studyprofile')),
            ],
            options={
                'verbose_name': 'Study Demographics',
                'verbose_name_plural': 'Study Demographics',
            },
        ),
    ]
