# Generated by Django 6.0.3 on 2026-03-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assessmenttoolusage_administration_timing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Uploaded PDF of the full paper.', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was uploaded.', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the PDF.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
